export const STATIC_PRODUCTS = [
    {
        id: 1,
        name: "Fresh Tomatoes",
        description: "Naturally grown, farm-fresh tomatoes.",
        price: 120,
        imageUrl: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce",
        category: "Vegetables",
        stock: 50,
        isFeatured: true,
    },
    {
        id: 2,
        name: "Organic Apples",
        description: "Crisp and sweet organic apples.",
        price: 180,
        imageUrl: "https://images.unsplash.com/photo-1567306301408-9b74779a11af",
        category: "Fruits",
        stock: 40,
        isFeatured: false,
    },
    {
        id: 3,
        name: "Farm Fresh Eggs",
        description: "Free-range eggs from local farms.",
        price: 90,
        imageUrl: "https://images.unsplash.com/photo-1587486913049-53fc88980cfc",
        category: "Dairy & Eggs",
        stock: 100,
        isFeatured: true,
    },
    {
        id: 4,
        name: "Raw Forest Honey",
        description: "Unprocessed natural honey.",
        price: 250,
        imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38",
        category: "Honey & Jams",
        stock: 30,
        isFeatured: false,
    },
    {
        id: 5,
        name: "Organic Wheat",
        description: "Stone-ground organic wheat grains.",
        price: 70,
        imageUrl: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec",
        category: "Grains",
        stock: 200,
        isFeatured: false,
    },
];
